services:
  - docker

script:
  - mkdir _site/
  - chmod 777 _site/
  - sudo chown 1000 -R $PWD
  - make buildimage build

deploy:
  provider: pages
  local-dir: _site
  skip-cleanup: true
  github-token: $GITHUB_TOKEN 
  keep-history: true
  on:
    branch: master
