title: http://altcomphsr.vshsr.ch/
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: ""
url: "http://altcomphsr.vshsr.ch/" # the base hostname & protocol for your site

exclude:
    - docker/
    - README.md
    - Makefile
    - deploy.sh
    - wercker.yml

host: 0.0.0.0

markdown: redcarpet
highlighter: rouge
redcarpet:
  extensions: ["fenced_code_blocks", "tables", "with_toc_data"]

# The documentation parts are stored as collections;
# that means, they are just a somewhat special page.
collections:
  hsr:
    output: true
  app:
    output: true

defaults:
  - scope: # content pages
      path: "pages"
    values:
      layout: "page"
      permalink: /:basename/
  - scope: # hsr collection
      type: hsr
      path: ""
    values:
      layout: "hsr"
      permalink: /hsr/:slug/
  - scope: # app collection
      type: app
      path: ""
    values:
      layout: "app"
      permalink: /app/:slug/
