title: http://altcomphsr.vshsr.ch/
description: > # this means to ignore newlines until "baseurl:"
  Wir fördern die Open Source Community und unterstützen dich bei
  der Benutzung deines alternativen Betriebssystems an der HSR.
baseurl: ""
url: "http://altcomphsr.vshsr.ch/" # the base hostname & protocol for your site

exclude:
    - docker/
    - Makefile
    - deploy.sh
    - wercker.yml

host: 0.0.0.0

markdown: redcarpet
highlighter: rouge
redcarpet:
  extensions: ["fenced_code_blocks", "tables", "with_toc_data"]

gems:
  - jemoji

# The documentation parts are stored as collections;
# that means, they are just a somewhat special page.
collections:
  hsr:
    output: true
  app:
    output: true

defaults:
  - scope: # content pages
      path: "tips"
      type: "posts"
    values:
      layout: "page"
      permalink: /:categories/:title/
  - scope: # content pages
      path: "pages"
    values:
      layout: "page"
      permalink: /:basename/
  - scope: # hsr collection
      type: hsr
      path: ""
    values:
      layout: "hsr"
      permalink: /hsr/:slug/
  - scope: # app collection
      type: app
      path: ""
    values:
      layout: "app"
      permalink: /app/:slug/
